FirstMVC/Controllers/FirstController.cs
using FirstMVC.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace FirstMVC.Controllers
{
    public class FirstController : Controller
    {
        // ViewData Dictionary
        [HttpGet]
        [Route("viewdata")]
        public ActionResult TestViewData()
        {
            List<SelectListItem> roles = new List<SelectListItem> {
                new SelectListItem { Text = "Admin", Value = "1" },
                new SelectListItem { Text = "Staff", Value = "2" },
                new SelectListItem { Text = "Customer Serice", Value = "3" },
                new SelectListItem { Text = "Teller", Value = "4" }
            };
            ViewBag.Roles = roles;
            ViewData.Add("user", "galihanggara");

            TempData.Add("temp", "Test Temporary");

            return View("Index");
        }

        [HttpGet]
        [Route("first")]
        public ActionResult Index()
        {
            HttpCookie cookie = new HttpCookie("user");
            cookie.Value = "Galih";
            cookie.Path = "/";
            cookie.Expires = DateTime.Now.AddMinutes(1);
            Response.Cookies.Add(cookie);
            return View();
        }

        // Bitwise
        [HttpGet]
        [Route("second")]
        public ActionResult Second()
        {
            ContentResult content = new ContentResult();
            content.Content = HttpContext.Request.Cookies["user"].Value;
            content.ContentType = "text/html";
            content.ContentEncoding = Encoding.ASCII;
            return content;
        }

        [Route("calculate/{num1}/{op}/{num2}")]
        public ActionResult Calculate(int num1, string op, int num2)
        {
            int result = 0;
            switch(op)
            {
                case "plus":
                    result = num1 + num2;
                    break;
                case "minus":
                    result = num1 - num2;
                    break;
                case "times":
                    result = num1 * num2;
                    break;
                case "divide":
                    result = num1 / num2;
                    break;
                case "mod":
                    result = num1 % num2;
                    break;
            }
            return Content("Result : " + result);
        }

        [HttpGet]
        [Route("model")]
        public ActionResult WithModel()
        {
            Person person = new Person();
            person.Name = "Galih";
            person.Address = "Tangerang";
            return View(person);
        }

        [HttpGet]
        [Route("listperson")]
        public ActionResult ListPerson()
        {
            List<Person> persons = new List<Person> {
                new Person() { Name = "Galih", Address = "Tangerang" },
                new Person() { Name = "Ujang", Address = "Bandung" },
                new Person() { Name = "Udin", Address = "Bogor" },
                new Person() { Name = "Ucup", Address = "Depok" },
                new Person() { Name = "Asep", Address = "Banten" }
            };

            // Views/First/ListPerson.cshtml
            return View(persons);
        }

        [HttpGet]
        [Route("person/{id}")]
        public ActionResult GetPerson(int id)
        {
            List<Person> persons = new List<Person> {
                new Person() { Name = "Galih", Address = "Tangerang" },
                new Person() { Name = "Ujang", Address = "Bandung" },
                new Person() { Name = "Udin", Address = "Bogor" },
                new Person() { Name = "Ucup", Address = "Depok" },
                new Person() { Name = "Asep", Address = "Banten" }
            };

            // Views/First/GetPerson.cshtml
            // Tipe dari persons[0] -> Person
            // int[] nums = {1, 2, 3};
            // Tipe nums[0] -> int
            return View("WithModel", persons[id]);
        }

        [HttpGet]
        [Route("edit/{id}")]
        public ActionResult EditForm(int id)
        {
            List<Person> persons = new List<Person> {
                new Person() { Id = 1, Name = "Galih", Address = "Tangerang" },
                new Person() { Id = 2,Name = "Ujang", Address = "Bandung" },
                new Person() { Id = 3,Name = "Udin", Address = "Bogor" },
                new Person() { Id = 4,Name = "Ucup", Address = "Depok" },
                new Person() { Id = 5,Name = "Asep", Address = "Banten" }
            };
            
            // Views/First/GetPerson.cshtml
            // Tipe dari persons[0] -> Person
            // int[] nums = {1, 2, 3};
            // Tipe nums[0] -> int
            return View(persons.First(f => f.Id == id));
        }

        [HttpPost]
        [Route("edit")]
        public ActionResult PostEdit(int id, Person person)
        {
            List<Person> persons = new List<Person> {
                new Person() { Id = 1, Name = "Galih", Address = "Tangerang" },
                new Person() { Id = 2, Name = "Ujang", Address = "Bandung" },
                new Person() { Id = 3, Name = "Udin", Address = "Bogor" },
                new Person() { Id = 4, Name = "Ucup", Address = "Depok" },
                new Person() { Id = 5, Name = "Asep", Address = "Banten" }
            };

            persons.First(f => f.Id == id).Address = person.Address;

            return View("ListPerson", persons);
        }

        [Route("test")]
        public string Test(Person person)
        {
            return person.Name + "-" + person.Address;
        }

        // Show Form
        [HttpGet]
        [Route("form")]
        public ActionResult Form()
        {
            return View();
        }

        // Post Form
        [HttpPost]
        [Route("form")]
        public ActionResult PostForm(Person person)
        {
            if(ModelState.IsValid)
            {
                return View("WithModel", person);
            }
            return View("Form");
        }


        [HttpGet]
        [Route("getperson")]
        public ActionResult GetPerson()
        {
            using(HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:61345");
                var get = client.GetAsync("/person");
                get.Wait();
                var result = get.Result;
                var data = result.Content.ReadAsStringAsync();
                data.Wait();
                var personJson = new JavaScriptSerializer().Deserialize<Dictionary<string, string>>(data.Result);
                Person person = new Person() { Name = personJson["Name"], Address = personJson["Address"] };

                return View("WithModel", person);
            }
        }
    }
}

FirstMVC/Views/First/EditForm.cshtml
@model FirstMVC.Models.Person

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Form Edit</title>
</head>
<body>
    <form method="post" action="~/edit"> 
        <input type="hidden" name="id" value="@Model.Id" />
        <input type="text" name="Name" placeholder="Name" value="@Model.Name"/>
        <input type="text" name="Address" placeholder="Address" value="@Model.Address" />
        <button type="submit">Post Data</button>
    </form>
</body>
</html>

FirstMVC/Views/First/Form.cshtml
@model FirstMVC.Models.Person

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Form</title>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    @using(Html.BeginForm("form", "First", FormMethod.Post, new { @class="form" }))
    {
        <div class="form-group">
            @Html.LabelFor(p => p.Name)
            @Html.TextBoxFor(p => p.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(p => p.Name)
        </div>
        <div class="form-group">
            @Html.LabelFor(p => p.Address)
            @Html.TextBoxFor(p => p.Address, new { @class = "form-control" })
            @Html.ValidationMessageFor(p => p.Address)
        </div>
        <button type="submit">Post Data</button>
    }
</body>
</html>

FirstMVC/Views/First/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        @Html.DropDownList("roles", (List<SelectListItem>)ViewBag.Roles)
    </div>
</body>
</html>

FirstMVC/Views/First/ListPerson.cshtml
@model IEnumerable<FirstMVC.Models.Person>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ListPerson</title>
</head>
<body>
    @TempData.Peek("temp")
    <table border="1">
        <thead>
            <tr>
                <th colspan="2">Persons</th>
            </tr>
            <tr>
                <th>Name</th>
                <th>Address</th>
            </tr>
        </thead> 
        <tbody>
            @foreach(var person in Model)
            {
                <tr>
                    <td>@person.Name</td>
                    <td>@person.Address</td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <th>Count : </th>
                <th>@Model.Count()</th>
            </tr>
        </tfoot>
    </table>
</body>
</html>

FirstMVC/Views/First/WithModel.cshtml
@model FirstMVC.Models.Person

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>WithModel</title>
</head>
<body>
    <div> 
        <h3>@Model.Name</h3>
        <h3>@Model.Address</h3>
    </div>
</body>
</html>